/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_toast_android_NativeString */

#ifndef _Included_com_toast_android_NativeString
#define _Included_com_toast_android_NativeString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_toast_android_NativeString
 * Method:    find
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_toast_android_NativeString_find
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_toast_android_NativeString
 * Method:    getBuffer
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_toast_android_NativeString_getBuffer
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_toast_android_NativeString
 * Method:    getString
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_toast_android_NativeString_getString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
